import type { Config } from "tailwindcss";

export default {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        cream: "#F9F8F6",
        paper: "#FFFFFF",
        ink: "#262626",
        "ink-soft": "#737373",
        orange: "#F85C15",
        blue: "#296FEC",
        lime: "#C9F040",
        pink: "#F5A0B5",
        background: "#F9F8F6",
        foreground: "#262626",
        card: "#FFFFFF",
        "card-foreground": "#262626",
        primary: "#262626",
        "primary-foreground": "#F9F8F6",
        secondary: "#296FEC",
        "secondary-foreground": "#262626",
        muted: "#F5F5F4",
        "muted-foreground": "#737373",
        accent: "#C9F040",
        "accent-foreground": "#262626",
        destructive: "#EF4444",
        "destructive-foreground": "#FFFFFF",
        border: "#262626",
        input: "#F5F5F4",
        ring: "#F85C15",
      },
      fontFamily: {
        sans: ["DMSans_400Regular", "sans-serif"],
        "sans-medium": ["DMSans_500Medium", "sans-serif"],
        "sans-semibold": ["DMSans_600SemiBold", "sans-serif"],
        "sans-bold": ["DMSans_700Bold", "sans-serif"],
        display: ["BricolageGrotesque_800ExtraBold", "sans-serif"],
        "display-bold": ["BricolageGrotesque_700Bold", "sans-serif"],
        "display-semibold": ["BricolageGrotesque_600SemiBold", "sans-serif"],
        mono: ["DMMono_400Regular", "monospace"],
        "mono-medium": ["DMMono_500Medium", "monospace"],
        italiana: ["Italiana_400Regular", "serif"],
        playfair: ["PlayfairDisplay_400Regular", "serif"],
      },
      borderRadius: {
        sm: "0.375rem",
        md: "0.625rem",
        lg: "0.85rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
    },
  },
  plugins: [],
} satisfies Config;
