import type { Config } from "tailwindcss";

export default {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        // Exact production tokens from restocking.app
        cream: "#fbf8f0",
        paper: "#ffffff",
        ink: "#0b0b0b",
        "ink-soft": "#5a5355",
        orange: "#ff803d",
        blue: "#369bff",
        lime: "#c8f23c",
        pink: "#ffa2b9",
        background: "#fbf8f0",
        foreground: "#0b0b0b",
        card: "#ffffff",
        "card-foreground": "#0b0b0b",
        primary: "#0b0b0b",
        "primary-foreground": "#fbf8f0",
        secondary: "#369bff",
        "secondary-foreground": "#0b0b0b",
        muted: "#f5f4f2",
        "muted-foreground": "#5a5355",
        accent: "#c8f23c",
        "accent-foreground": "#0b0b0b",
        destructive: "#ee3533",
        "destructive-foreground": "#ffffff",
        border: "#0b0b0b",
        input: "#e6e4e1",
        ring: "#ff803d",
      },
      fontFamily: {
        sans: ["DMSans_400Regular", "sans-serif"],
        "sans-medium": ["DMSans_500Medium", "sans-serif"],
        "sans-semibold": ["DMSans_600SemiBold", "sans-serif"],
        "sans-bold": ["DMSans_700Bold", "sans-serif"],
        display: ["BricolageGrotesque_800ExtraBold", "sans-serif"],
        "display-bold": ["BricolageGrotesque_700Bold", "sans-serif"],
        "display-semibold": ["BricolageGrotesque_600SemiBold", "sans-serif"],
        mono: ["DMMono_400Regular", "monospace"],
        "mono-medium": ["DMMono_500Medium", "monospace"],
        italiana: ["Italiana_400Regular", "serif"],
        playfair: ["PlayfairDisplay_400Regular", "serif"],
      },
      borderRadius: {
        sm: "0.375rem",
        md: "0.625rem",
        lg: "0.85rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
    },
  },
  plugins: [],
} satisfies Config;
